# Generated by Django 4.1.7 on 2023-03-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_alter_animalsranch_charateristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalsranch',
            name='description',
        ),
    ]
