# Generated by Django 4.1.7 on 2023-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_remove_animalsranch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsranch',
            name='Charateristics',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='animalsranch',
            name='Statistics',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
