# Generated by Django 4.1.7 on 2023-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_alter_animalsranch_charateristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
