# Generated by Django 4.1.7 on 2023-04-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='comment',
        ),
    ]
